## See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  # - id: isort
  #   name: isort
  #   entry: isort
  #   language: system
  #   types: [python]
  #   stages: [commit]
  - id: black
    name: black
    language: system
    entry: black
    types: [python]
    stages: [commit]
  - id: pytest
    name: pytest
    language: system
    entry: pytest --cov
    pass_filenames: false
    always_run: true
    stages: [push]